import { env } from './env'
export type CreatePRInput = {
  repoUrl: string
  driftId: string
  resourceType: string
  resourceId: string
  attribute: string
  desiredValue: string
  actualValue: string
  riskLevel: string
  explanation: string
}

type GitHubRepo = {
  default_branch?: string
}

type GitHubRef = {
  object?: {
    sha?: string
  }
}

type GitHubContent = {
  sha?: string
}

type GitHubPullRequest = {
  html_url?: string
}

const GITHUB_API_VERSION = '2022-11-28'
const GITHUB_ACCEPT = 'application/vnd.github+json'

function parseGitHubRepo(repoUrl: string): { owner: string; repo: string } {
  let path = repoUrl.trim()

  try {
    path = new URL(path).pathname
  } catch {
    path = path.replace(/^git@github\.com:/, '')
  }

  const segments = path
    .replace(/\.git$/, '')
    .split('/')
    .map((segment) => segment.trim())
    .filter(Boolean)

  if (segments.length < 2) {
    throw new Error(`Invalid repo URL: ${repoUrl}`)
  }

  const [owner, repo] = segments.slice(-2)
  if (!owner || !repo) {
    throw new Error(`Invalid repo URL: ${repoUrl}`)
  }

  return { owner, repo }
}

function githubHeaders(token: string): HeadersInit {
  return {
    Authorization: `Bearer ${token}`,
    Accept: GITHUB_ACCEPT,
    'X-GitHub-Api-Version': GITHUB_API_VERSION
  }
}

async function githubRequest<T>(token: string, method: string, url: string, body?: unknown): Promise<T> {
  const response = await fetch(url, {
    method,
    headers: {
      ...githubHeaders(token),
      ...(body === undefined ? {} : { 'Content-Type': 'application/json' })
    },
    body: body === undefined ? undefined : JSON.stringify(body)
  })

  if (!response.ok) {
    const responseBody = await response.text()
    throw new Error(`GitHub API ${response.status} on ${method} ${url}: ${responseBody}`)
  }

  return (await response.json()) as T
}

async function githubFetch(token: string, method: string, url: string, body?: unknown): Promise<Response> {
  return fetch(url, {
    method,
    headers: {
      ...githubHeaders(token),
      ...(body === undefined ? {} : { 'Content-Type': 'application/json' })
    },
    body: body === undefined ? undefined : JSON.stringify(body)
  })
}

async function throwGitHubError(response: Response, method: string, url: string): Promise<never> {
  const responseBody = await response.text()
  throw new Error(`GitHub API ${response.status} on ${method} ${url}: ${responseBody}`)
}

function buildFixMarkdown(input: CreatePRInput): string {
  const explanation = input.explanation.trim() || 'Run /explain to generate AI analysis.'

  return `# SynchroIaC Drift Fix

**Drift ID:** ${input.driftId}
**Resource:** ${input.resourceType} / ${input.resourceId}
**Risk Level:** ${input.riskLevel}

## What Changed
Attribute \`${input.attribute}\` has drifted from the Terraform-declared
value.

| | Value |
|---|---|
| **Terraform declares** | \`${input.desiredValue}\` |
| **AWS actual value** | \`${input.actualValue}\` |

## Explanation
${explanation}

## Suggested Fix
Update your Terraform configuration to reconcile this drift.

Option A — Accept the change (update Terraform to match AWS):
\`\`\`hcl
# Update ${input.resourceType} "${input.resourceId}"
resource "${input.resourceType}" "this" {
  ${input.attribute} = "${input.actualValue}"
}
\`\`\`

Option B — Revert the change (run Terraform apply to restore declared state):
\`\`\`bash
terraform apply -target=${input.resourceType}.${input.resourceId}
\`\`\`

---
*Generated by [SynchroIaC](https://synchroiac.vercel.app)*
`
}

export async function createDriftFixPR(input: CreatePRInput): Promise<string> {
  const { owner, repo } = parseGitHubRepo(input.repoUrl)
  const token = env.GITHUB_TOKEN
  if (!token) {
    throw new Error('Missing GITHUB_TOKEN')
  }

  const repoApiUrl = `https://api.github.com/repos/${owner}/${repo}`
  const repoData = await githubRequest<GitHubRepo>(token, 'GET', repoApiUrl)
  const defaultBranch = repoData.default_branch
  if (!defaultBranch) {
    throw new Error(`GitHub API response missing default_branch on GET ${repoApiUrl}`)
  }

  const defaultBranchRefUrl = `${repoApiUrl}/git/ref/heads/${defaultBranch}`
  const defaultBranchRef = await githubRequest<GitHubRef>(token, 'GET', defaultBranchRefUrl)
  const latestSha = defaultBranchRef.object?.sha
  if (!latestSha) {
    throw new Error(`GitHub API response missing object.sha on GET ${defaultBranchRefUrl}`)
  }

  const branchName = `synchroiac/fix-${input.driftId.slice(0, 8)}`
  const createRefUrl = `${repoApiUrl}/git/refs`
  const createRefResponse = await githubFetch(token, 'POST', createRefUrl, {
    ref: `refs/heads/${branchName}`,
    sha: latestSha
  })
  if (!createRefResponse.ok && createRefResponse.status !== 422) {
    await throwGitHubError(createRefResponse, 'POST', createRefUrl)
  }

  const filePath = `synchroiac-fixes/drift-${input.driftId}.md`
  const fileContent = buildFixMarkdown(input)
  const contentsUrl = `${repoApiUrl}/contents/${filePath}`
  const putFileBody = {
    message: `fix: SynchroIaC drift reconciliation for ${input.resourceId}`,
    content: Buffer.from(fileContent, 'utf8').toString('base64'),
    branch: branchName
  }

  const putFileResponse = await githubFetch(token, 'PUT', contentsUrl, putFileBody)
  if (!putFileResponse.ok) {
    if (putFileResponse.status !== 422) {
      await throwGitHubError(putFileResponse, 'PUT', contentsUrl)
    }

    const getFileUrl = `${contentsUrl}?ref=${encodeURIComponent(branchName)}`
    const existingFile = await githubRequest<GitHubContent>(token, 'GET', getFileUrl)
    if (!existingFile.sha) {
      throw new Error(`GitHub API response missing sha on GET ${getFileUrl}`)
    }

    await githubRequest(token, 'PUT', contentsUrl, { ...putFileBody, sha: existingFile.sha })
  }

  const createPullUrl = `${repoApiUrl}/pulls`
  const createPullResponse = await githubFetch(token, 'POST', createPullUrl, {
    title: `[SynchroIaC] Fix ${input.riskLevel} drift: ${input.resourceType}/${input.attribute}`,
    body: fileContent.slice(0, 500),
    head: branchName,
    base: defaultBranch
  })

  if (!createPullResponse.ok) {
    if (createPullResponse.status !== 422) {
      await throwGitHubError(createPullResponse, 'POST', createPullUrl)
    }

    const pullsUrl = `${createPullUrl}?head=${encodeURIComponent(`${owner}:${branchName}`)}&state=open`
    const existingPulls = await githubRequest<GitHubPullRequest[]>(token, 'GET', pullsUrl)
    const existingPullUrl = existingPulls[0]?.html_url
    if (!existingPullUrl) {
      await throwGitHubError(createPullResponse, 'POST', createPullUrl)
    }
    return existingPullUrl
  }

  const createdPull = (await createPullResponse.json()) as GitHubPullRequest
  if (!createdPull.html_url) {
    throw new Error(`GitHub API response missing html_url on POST ${createPullUrl}`)
  }

  return createdPull.html_url
}
